name: Client

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    
    - name: Install all NPM packages
      run: yarn
    
    - name: Install all client packages
      working-directory: ./client
      run: yarn
    
    - name: Terser fix
      continue-on-error: true
      # working-directory: ./client
      run: cp ./node_modules/terser/dist/bundle.js ./node_modules/terser/dist/bundle.min.js
    
    - name: Build project
      continue-on-error: true
      working-directory: ./client
      run: yarn build

    - name: Upload build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./client/dist
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download build files
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./client/dist

    - name: Deploy to gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./client/dist